spring:
  application:
    name: restaurante
  config:
    import: optional:file:.env[.properties]

  # Configuración ACID (PostgreSQL)
  datasource:
    url: jdbc:postgresql://localhost:5433/restaurante_db
    username: postgres
    password: password # TODO: Change to real password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Configuración BASE (MongoDB)
  data:
    mongodb:
      uri: mongodb://localhost:27017/restaurante_historico

  # Configuración JWT
  jwt:
    secret: TXkgc3VwZXIgc2VjcmV0IGtleSBwYXJhIGVsIHJlc3RhdXJhbnRl
    expiration-ms: 3600000

  # Configuración OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

server:
  port: 8443
  ssl:
    key-store: classpath:restaurante.p12
    key-store-password: ${SSL_KEYSTORE_PASSWORD}
    key-store-type: PKCS12
    key-alias: restaurante

logging:
  level:
    root: INFO
    com.dows.bitacora2.restaurante: DEBUG
    org.springframework.web: WARN
